name: examples
on: [push, pull_request]
jobs:
  linux:
    strategy:
      matrix:
        arch: [x86_64]
        os: [linux]
        frida_version: ["16.0.2"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: ./.github/actions/install-frida-devkit
        with:
          arch: ${{ matrix.arch }}
          os: ${{ matrix.os }}
          version: ${{ matrix.frida_version }}
      - run: |
          for example in ./examples/*; do
            go build "$example"
          done
